version: '3.8'

services:
  db:
    image: postgres:15
    container_name: odoo_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - odoo_net

  odoo:
    image: odoo:17
    container_name: odoo_app
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./data/odoo:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - ./logs:/var/log/odoo
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - odoo_net

networks:
  odoo_net:
    driver: bridge